# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

contact:
  url:  /contact
  param: { module: contact, action: index }

family:
  url:  /family
  param: { module: family, action: index }
  
family_artist:
  url: /family/:slug.html
  param: { module: family, action: show}
  class:   sfDoctrineRoute
  options: { model: Family, type: object }
  requirements:
    sf_method: [get, post]

family_photo:
  url: /family/:slug.html
  param: { module: family, action: show}
  class:   sfDoctrineRoute
  options: { model: Family, type: object }
  requirements:
    sf_method: [get, post]

family_graph:
  url: /family/:slug.html
  param: { module: family, action: show}
  class:   sfDoctrineRoute
  options: { model: Family, type: object }
  requirements:
    sf_method: [get, post]

family_show:
  url: /family/:slug.html
  param: { module: family, action: show}
  class:   sfDoctrineRoute
  options: { model: Family, type: object }
  requirements:
    sf_method: [get, post]

news:
  url:  /news
  param: { module: news, action: index }
  
shop:
  url:  /shop
  param: { module: shop, action: index }
  
news_show:
  url: /news/:slug.html
  param: { module: news, action: show}
  class:   sfDoctrineRoute
  options: { model: Article, type: object }
  requirements:
    sf_method: [get, post]
  
shop_show:
  url: /shop/:slug.html
  param: { module: shop, action: show}
  class:   sfDoctrineRoute
  options: { model: Product, type: object }
  requirements:
    sf_method: [get, post]

# default rules
homepage:
  url:   /
  param: { module: news, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
